name: vnatpro2
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  mobx: ^2.1.0
  flutter_mobx: ^2.0.6+4
  mobx_codegen: ^2.0.7+3
  google_fonts: ^3.0.1
  intl: ^0.17.0
  cached_network_image: ^3.2.2
  google_maps_flutter: ^2.2.1
  flutter_svg: ^1.1.5
  shared_preferences: ^2.0.15
  http: ^0.13.5
  provider: ^6.0.3
  flutter_spinkit: ^5.1.0
  camera: ^0.10.0+3
  geolocator: ^9.0.2
  google_geocoding: ^0.2.0
  nb_utils: ^4.6.21
  html: ^0.15.0
  analog_clock: ^0.1.1
  maps_toolkit: ^2.0.1

  cupertino_icons: ^1.0.2
  carousel_slider: ^4.1.1
  slide_digital_clock: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.2.1

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - images/splashscreen/
    - images/login/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
